name: acn
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - opencv
  - python=3.8
  - pytorch=1.7.1
  - torchvision=0.8.2 
  - cudatoolkit=11.0
  - pytorch-lightning=1.1.6
  - matplotlib
  - jupyter
  - notebook
  - pytest
  - pip
  - mediapipe
